-- MySQL Script generated by MySQL Workbench
-- Tue Jul 17 16:12:09 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema CFE
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CFE
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_cfe` DEFAULT CHARACTER SET utf8 ;
USE `db_cfe` ;

-- -----------------------------------------------------
-- Table `CFE`.`Datos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cfe`.`Datos` (
  `Division` VARCHAR(10) NULL,
  `Zona` VARCHAR(10) NULL,
  `Status` VARCHAR(10) NULL,
  `Numero` INT NULL,
  `Año` INT NULL,
  `Mes` INT NULL,
  `Area` VARCHAR(10) NULL,
  `Ciudad` VARCHAR(10) NULL,
  `SE` VARCHAR(10) NULL,
  `Circuito` INT NULL,
  `Fecha_Inici` VARCHAR(20) NULL,
  `Fecha_Term` VARCHAR(20) NULL,
  `Hora_Ini` VARCHAR(15) NULL,
  `Hora_Term` VARCHAR(15) NULL,
  `Demanda` INT NULL,
  `Usuario` INT NULL,
  `Ramal` VARCHAR(15) NULL,
  `PUR` INT NULL,
  `Material` VARCHAR(15) NULL,
  `Causa` VARCHAR(15) NULL,
  `Entidad` VARCHAR(15) NULL,
  `Proceso` VARCHAR(15) NULL,
  `Continuada` VARCHAR(15) NULL,
  `DEMUA` INT NULL,
  `Duracion` INT(15) NULL,
  `TIU` FLOAT NULL,
  `Usuario_Promedio` INT(15) NULL,
  `TLU_Real` FLOAT NULL,
  `EDV` FLOAT NULL,
  `Afectacion` VARCHAR(15) NULL,
  `Tipo_Tramo` VARCHAR(15) NULL,
  `Tramo_Trocal` INT(10) NULL,
  `Tramo_Ramal` VARCHAR(15) NULL,
  `Atendido_Por` VARCHAR(15) NULL,
  `Con_Sin_Evento` VARCHAR(15) NULL,
  `Num_Evento` INT(10) NULL,
  `Falla_Renuante` VARCHAR(15) NULL,
  `Solicitud` INT(10) NULL,
  `Orden_Sicoss` VARCHAR(25) NULL,
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
