<center>
	<h1>SAIFI</h1>
</center>
<div class="container">
	<table class="table table-striped">
		<thead>
			 <tr>
       <th>AREAS</th>
       <th></th>
       <th>Ene</th>
       <th>Feb</th>
       <th>Mar</th>
       <th>Abr</th>
       <th>May</th>
       <th>Jun</th>
       <th>Jul</th>
       <th>Ago</th>
       <th>Sep</th>
       <th>Oct</th>
       <th>Nov</th>
       <th>Dic</th>
       <th>Total</th>
     	</tr>
     	<tr>
      <th>FORANEA</th>
      <th>META</th>
      <th>0.004</th>
      <th>0.002</th>
      <th>0.006</th>
      <th>0.015</th>
      <th>0.031</th>
      <th>0.018</th>
      <th>0.008</th>
      <th>0.014</th>
      <th>0.007</th>
      <th>0.015</th>
      <th>0.008</th>
      <th>0.006</th>
      <th>0.13</th>
    </tr>
		</thead>
		<tbody>
			<tr>
			 <td></td>
    		 <td>REAL</td>
    		 @foreach($foranea as $fora)
    		 <td>{{$fora->SAIFI}}</td>
    		 @endforeach
    		 </tr>
    		 <tr class="red accent-2" style="color:white">
			 <td>Total</td>
    		 <td>=</td><td>=</td><td>=</td><td>=</td><td>=</td><td>=</td><td>=</td>
    		 <td>=</td><td>=</td><td>=</td><td>=</td><td>=</td><td>=</td>
    		 @foreach($Totalforanea as $total)
    		 <td>{{$total->SAIFI}}</td>
    		 @endforeach
    		 </tr>
    		 <tr>
      <th>URBANA</th>
      <th>META</th>
      <th>0.004</th>
      <th>0.002</th>
      <th>0.006</th>
      <th>0.016</th>
      <th>0.029</th>
      <th>0.020</th>
      <th>0.007</th>
      <th>0.015</th>
      <th>0.010</th>
      <th>0.014</th>
      <th>0.009</th>
      <th>0.005</th>
      <th>0.14</th>
    </tr>
    <tr>
			 <td></td>
    		 <td>REAL</td>
    		 @foreach($urbana as $urba)
    		 <td>{{$urba->SAIFI}}</td>
    		 @endforeach
    		 </tr>
    		 <tr class="red accent-2" style="color:white">
    		 <td>Total</td>
    		 <td>=</td><td>=</td><td>=</td><td>=</td><td>=</td><td>=</td><td>=</td>
    		 <td>=</td><td>=</td><td>=</td><td>=</td><td>=</td><td>=</td>
    		 @foreach($Total as $t)
    		 <td>{{$t->SAIFI}}</td>
    		 @endforeach
    		 </tr>
    		  <tr>
      <th>VILLAFLORES</th>
      <th>META</th>
      <th>0.002</th>
      <th>0.002</th>
      <th>0.005</th>
      <th>0.012</th>
      <th>0.029</th>
      <th>0.017</th>
      <th>0.006</th>
      <th>0.013</th>
      <th>0.007</th>
      <th>0.012</th>
      <th>0.006</th>
      <th>0.005</th>
      <th>0.12</th>
    </tr>
    <tr>
			 <td></td>
    		 <td>REAL</td>
    		 @foreach($villaflores as $villa)
    		 <td>{{$villa->SAIFI}}</td>
    		 @endforeach
    		 </tr>
    		 <tr class="red accent-2" style="color:white">
    		 <td>Total</td>
    		 <td>=</td><td>=</td><td>=</td><td>=</td><td>=</td><td>=</td><td>=</td>
    		 <td>=</td><td>=</td><td>=</td><td>=</td><td>=</td><td>=</td>
    		 @foreach($totalvillaflores as $t)
    		 <td>{{$t->SAIFI}}</td>
    		 @endforeach
    		 </tr>
    		 <tr>
      <th>CINTALAPA</th>
      <th>META</th>
      <th>0.004</th>
      <th>0.002</th>
      <th>0.005</th>
      <th>0.014</th>
      <th>0.018</th>
      <th>0.013</th>
      <th>0.004</th>
      <th>0.013</th>
      <th>0.007</th>
      <th>0.010</th>
      <th>0.003</th>
      <th>0.003</th>
      <th>0.10</th>
    </tr>
    <tr>
			 <td></td>
    		 <td>REAL</td>
    		 @foreach($cintalapa as $cinta)
    		 <td>{{$cinta->SAIFI}}</td>
    		 @endforeach
    		 </tr>
    		 <tr class="red accent-2" style="color:white">
    		 <td>Total</td>
    		 <td>=</td><td>=</td><td>=</td><td>=</td><td>=</td><td>=</td><td>=</td>
    		 <td>=</td><td>=</td><td>=</td><td>=</td><td>=</td><td>=</td>
    		 @foreach($totalcinta as $t)
    		 <td>{{$t->SAIFI}}</td>
    		 @endforeach
    		 </tr>
    		  <tr>
      <th>BOCHIL</th>
      <th>META</th>
      <th>0.003</th>
      <th>0.002</th>
      <th>0.003</th>
      <th>0.011</th>
      <th>0.014</th>
      <th>0.009</th>
      <th>0.003</th>
      <th>0.008</th>
      <th>0.006</th>
      <th>0.009</th>
      <th>0.003</th>
      <th>0.002</th>
      <th>0.07</th>
    </tr>
    <tr>
			 <td></td>
    		 <td>REAL</td>
    		 @foreach($bochil as $bo)
    		 <td>{{$bo->SAIFI}}</td>
    		 @endforeach
    </tr>
    <tr class="red accent-2" style="color:white">
    		 <td>Total</td>
    		 <td>=</td><td>=</td><td>=</td><td>=</td><td>=</td><td>=</td><td>=</td>
    		 <td>=</td><td>=</td><td>=</td><td>=</td><td>=</td><td>=</td>
    		 @foreach($totalbochil as $t)
    		 <td>{{$t->SAIFI}}</td>
    		 @endforeach
    		 </tr>
    		  <tr>
      <th>W</th>
      <th>META</th>
      <th>0.000</th>
      <th>0.000</th>
      <th>0.000</th>
      <th>0.000</th>
      <th>0.000</th>
      <th>0.000</th>
      <th>0.000</th>
      <th>0.000</th>
      <th>0.000</th>
      <th>0.000</th>
      <th>0.000</th>
      <th>0.000</th>
      <th>0.000</th>
    </tr>
     <tr>
			 <td></td>
    		 <td>REAL</td>
    		 @foreach($lts as $lts)
    		 <td>{{$lts->SAIFI}}</td>
    		 @endforeach
    </tr>
     <tr class="red accent-2" style="color:white">
    		 <td>Total</td>
    		 <td>=</td><td>=</td><td>=</td><td>=</td><td>=</td><td>=</td><td>=</td>
    		 <td>=</td><td>=</td><td>=</td><td>=</td><td>=</td><td>=</td>
    		 @foreach($totallts as $l)
    		 <td>{{$l->SAIFI}}</td>
    		 @endforeach
    		 </tr>
    		  <tr>
      <th>Lineas</th>
      <th>META</th>
      <th>0.000</th>
      <th>0.000</th>
      <th>0.000</th>
      <th>0.000</th>
      <th>0.000</th>
      <th>0.000</th>
      <th>0.000</th>
      <th>0.000</th>
      <th>0.000</th>
      <th>0.000</th>
      <th>0.000</th>
      <th>0.000</th>
      <th>0.000</th>
    </tr>
    <tr>
    	<td></td>
    	<td>REAL</td>
    	<td>0.000</td>
    	<td>0.000</td>
    	<td>0.000</td>
    	<td>0.000</td>
    	<td>0.000</td>
    	<td>0.000</td>
    	<td>0.000</td>
    	<td>0.000</td>
    	<td>0.000</td>
    	<td>0.000</td>
    	<td>0.000</td>
    	<td>0.000</td>
    	<td>0.000</td>
    </tr>
    <tr>
      <th>Protecciones</th>
      <th>META</th>
      <th>0.000</th>
      <th>0.000</th>
      <th>0.000</th>
      <th>0.000</th>
      <th>0.000</th>
      <th>0.000</th>
      <th>0.000</th>
      <th>0.000</th>
      <th>0.000</th>
      <th>0.000</th>
      <th>0.000</th>
      <th>0.000</th>
      <th>0.000</th>
    </tr>
    <tr>
    	<td></td>
    	<td>REAL</td>
    	<td>0.000</td>
    	<td>0.000</td>
    	<td>0.000</td>
    	<td>0.000</td>
    	<td>0.000</td>
    	<td>0.000</td>
    	<td>0.000</td>
    	<td>0.000</td>
    	<td>0.000</td>
    	<td>0.000</td>
    	<td>0.000</td>
    	<td>0.000</td>
    	<td>0.000</td>
    </tr>
    <tr>
      <th>Subesta</th>
      <th>META</th>
      <th>0.000</th>
      <th>0.000</th>
      <th>0.000</th>
      <th>0.000</th>
      <th>0.000</th>
      <th>0.000</th>
      <th>0.000</th>
      <th>0.000</th>
      <th>0.000</th>
      <th>0.000</th>
      <th>0.000</th>
      <th>0.000</th>
      <th>0.000</th>
    </tr>
    <tr>
    	<td></td>
    	<td>REAL</td>
    	<td>0.000</td>
    	<td>0.000</td>
    	<td>0.000</td>
    	<td>0.000</td>
    	<td>0.000</td>
    	<td>0.000</td>
    	<td>0.000</td>
    	<td>0.000</td>
    	<td>0.000</td>
    	<td>0.000</td>
    	<td>0.000</td>
    	<td>0.000</td>
    	<td>0.000</td>
    </tr>
    <tr>
      <th>Control</th>
      <th>META</th>
      <th>0.000</th>
      <th>0.000</th>
      <th>0.000</th>
      <th>0.000</th>
      <th>0.000</th>
      <th>0.000</th>
      <th>0.000</th>
      <th>0.000</th>
      <th>0.000</th>
      <th>0.000</th>
      <th>0.000</th>
      <th>0.000</th>
      <th>0.000</th>
    </tr>
    <tr>
    	<td></td>
    	<td>REAL</td>
    	<td>0.000</td>
    	<td>0.000</td>
    	<td>0.000</td>
    	<td>0.000</td>
    	<td>0.000</td>
    	<td>0.000</td>
    	<td>0.000</td>
    	<td>0.000</td>
    	<td>0.000</td>
    	<td>0.000</td>
    	<td>0.000</td>
    	<td>0.000</td>
    	<td>0.000</td>
    </tr>
    <tr>
      <th>Meta Mensual</th>
      <th>META</th>
      <th>0.017</th>
      <th>0.010</th>
      <th>0.025</th>
      <th>0.068</th>
      <th>0.121</th>
      <th>0.077</th>
      <th>0.028</th>
      <th>0.063</th>
      <th>0.037</th>
      <th>0.060</th>
      <th>0.029</th>
      <th>0.021</th>
      <th>0.556</th>
    </tr>
    <tr>
			 <td></td>
    		 <td>REAL</td>
    		 @foreach($meta_mes as $meta)
    		 <td>{{$meta->SAIFI}}</td>
    		 @endforeach
    </tr>
    <tr class="red accent-2" style="color:white">
    		 <td>Total</td>
    		 <td>=</td><td>=</td><td>=</td><td>=</td><td>=</td><td>=</td><td>=</td>
    		 <td>=</td><td>=</td><td>=</td><td>=</td><td>=</td><td>=</td>
    		 @foreach($total_meta as $meta)
    		 <td>{{$meta->SAIFI}}</td>
    		 @endforeach
    		 </tr>


		</tbody>
	</table>
</div>
